### ISSUE TITLE
Issues with friction representation on Flow screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fluid-pressure-and-flow#326] opened 2019-07-15 16:46 UTC
For #325 

A user reported:
> To whom it may concern:
>
>I am a science content reviewer for resources which are posted on a web site for teachers:   http://www.cpalms.org/resources/ResourceSearch.aspx
>
>In your simulation at: 
http://phet.colorado.edu/en/simulation/fluid-pressure-and-flow  
the “Flow” simulation when” friction” in added is wrong in the following sense.  To have flow down a horizontal pipe when there is friction then a horizontal pressure gradient in the fluid must exist.  That is, for example, the pressure at the opening of the pipe at the left must be greater, at the same level, than that at the pipe exit.  The pressures in your “friction” simulation are only hydrostatic.  For the simulated frictional flow there must be a constant, negative pressure gradient down the pipe.
>
>Please let me know if this site is ever modified as per the above comment.  

Oliver replied 6/23/13
>We met on Thursday and agree that this issue will need to be fixed. We are planning to port this simulation to HTML5 and will fix this issue in the redesign. We estimate the port will be redesigned and released in the next year.
>
>Read more about our HTML5 conversion effort: http://phet.colorado.edu/2013/the-future-of-phet
>
>Thanks for pointing this issue out!

This seems like an issue that merits further discussion. As far as I can tell, no changes were made based on this user feedback. @kathy-phet @ariel-phet?

**Comment by arouinfar** [comment] 2019-07-16 16:56
Potentially related to #319.

**Comment by ariel-phet** [comment] 2019-07-24 00:47
duplicate of #314

**Closed** 2019-07-24 00:47 UTC
Labels: design:general, type:duplicate, type:user-feedback
